version: '3.4'


services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  gwizdserwis:
    image: ${DOCKER_REGISTRY-}gwizdserwis
    build:
      context: .
      dockerfile: GwizdSerwis/Dockerfile
    environment:
      ConnectionStrings__SqlConnection: "Server=sql-server,1433;Database=appdb;User Id=sa;Password=StrongPassword123!;Encrypt=False;"

volumes:
  sqlserver-data:
    driver: local
